### ISSUE TITLE
Lambda in web.py to work with python3

### ISSUE THREAD

**Issue by desprit** [lamflam/rq-scheduler-dashboard#1]
Hi!

This line:
`jobs = filter(lambda (job, _): job.origin == queue_name, jobs)`
in web.py:163 doesn't work with python3 because parenthesis syntax was remove. Instead it should probably look like:
`jobs = filter(lambda job_: job_[0].origin == queue_name, jobs)`
at least, I was able to make it work this way :)

**Comment by lamflam** [comment]
Hey @desprit, good catch. Mind opening a PR to make the change and I'll pull it in? TBH, I'm only fairly familiar with all of this code because I mostly pulled together code from `rq-dashboard` and @helenst's PR to add scheduler support into it's own package, but I'm happy to pull in your change and publish a new version.

**Comment by helenst** [comment]
I guess it was originally my code (and I only ever ran it with python2) - suggested change looks good from here :)

**Comment by desprit** [comment]
Hi guys!
Thank you for joining discussion :) I created pull request.

**Comment by sobolevn** [comment]
This is still not released in pypi.

**Comment by lamflam** [comment]
@sobolevn You're right, I just published this release to pypi.
